### ISSUE TITLE
Incorrect expectation values for the identity observable

### ISSUE THREAD

**Issue by mberna** [qiskit-community/prototype-zne#58]
### Device

MacBook Pro

### OS

macOS Sonoma 14.0

### Python version

3.11.7

### Release version or branch/commit

1.2.2

### What is the current behavior?

The expectation values returned by the ZNEEstimator are not correct for this particular example. I'm including the results of the "reference implementation" of the Estimator in `qiskit.primitives` and the exp values differ greatly.

### What is the expected behavior?

Expectation values return by the ZNEEstimator are similar to the reference implementation.

### Steps to reproduce the problem

```python
from qiskit.circuit.library import RealAmplitudes
from qiskit.quantum_info import SparsePauliOp
from qiskit.primitives import BackendEstimator, Estimator as RefEstimator
from qiskit.providers.fake_provider import FakeBogota
from zne import zne, ZNEStrategy
from zne.noise_amplification import TwoQubitAmplifier

ZNEEstimator = zne(BackendEstimator)
fake_nairobi = FakeBogota()

circuit = RealAmplitudes(num_qubits=5, reps=2, entanglement="full")
num_parameters = circuit.num_parameters
observable = SparsePauliOp("IIIII")
parameter_values = [[0] * num_parameters]

# Reference estimator
ref_job = RefEstimator().run(circuit, observable, parameter_values)
ref_result = ref_job.result()
print("ref result:", ref_result.values)

# ZNE estimator
zne_strategy = ZNEStrategy(noise_factors=[1, 3, 5], noise_amplifier=TwoQubitAmplifier())
zne_estimator = ZNEEstimator(backend=fake_nairobi)
zne_job = zne_estimator.run(circuit, observable, parameter_values, zne_strategy=zne_strategy)
zne_result = zne_job.result()
print("zne result", zne_result.values)

```

### Context

Tested this example with different versions of the library and the `1.0.0` was the last version that produced correct results.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pedrorrivero** [comment]
Thanks for reporting this @mberna, read below for my initial assessment (c.c. @1ucian0). 

> [!NOTE]
> Because of the nature of this issue, it is very limited in scope and unlikely to affect anything other than trivial computations or misuses of the tool (e.g. to mitigate errors on an zero-noise/ideal simulator).

### Observations

1. Because the observable is the trivial one (i.e. `III...`), the expectation value is always `1.0` with variance `0.0` regardless of the circuit, (level of) noise, or anything else. Because of this null variance, the `scipy.curvefit` extrapolation fails while trying to compute the induced error bar —a feature that came out in version `1.1.0`.

2. Real world cases where the variance is zero are _highly unlikely_ to occur —if they ever do— since they arise in scenarios where the computation is fully deterministic. Because of this, the issue is very limited in scope and unlikely to affect anything other than trivial computations or misuses of the tool (e.g. to mitigate errors on an zero-noise/ideal simulator).

3. In the following line you are requesting to amplify the noise _only_ on two-qubit gates:
    ```python
    zne_strategy = ZNEStrategy(noise_factors=[1, 3, 5], noise_amplifier=TwoQubitAmplifier())
    ```
    Since there are no such gates in your circuit (before decomposition), the noise amplification fails with a warning:
    ```sh
    UserWarning: Noise amplification is not performed since none of the gates are folded.
    ```
    
4. `TwoQubitAmplifier` is the default behavior if no explicit amplifier is passed since version `1.0.0rc0` —improving upon the previous default `CxAmplifier` which only addresses CNOT gates. This is especially intended for use with already transpiled circuits, where all gates are going to be either one or two-qubit gates. For this particular case, something like the vanilla `LocalFoldingAmplifier` or `GlobalFoldingAmplifier` would be more suited.


### Next steps

- [ ] Update the extrapolator(s) to handle cases with zero variance smoothly.
- [ ] Build a new `MultiQubitAmplifier` which will amplify noise in all gates with `num_qubits >= 2`.
- [ ] Set such `MultiQubitAmplifier` as the new default in `ZNEStrategy`.

Please, let me know if you agree to this and I will proceed.

**Comment by mberna** [comment]
> - [ ] Update extrapolator(s) to handle zero variance smoothly, introducing support for the identity observable.

I would prioritize this step over the other two. The rest sounds good to me.

**Comment by pedrorrivero** [comment]
> Update extrapolator(s) to handle zero variance smoothly, introducing support for the identity observable.

Accomplished in: c1f535ff7ac1236a94be243b59549e9160cd2481
